version = require './lib' .VERSION
console.log """
// Generated by LiveScript 1.2.0

// prelude.ls #version
// Copyright (c) George Zahariev
// Released under the MIT License
// https://raw.githubusercontent.com/gkz/prelude-ls/master/LICENSE
"""
