version = require './lib' .VERSION
{VERSION: ls-version} = require 'livescript'
console.log """
// Generated by LiveScript #ls-version

// prelude.ls #version
// Copyright (c) George Zahariev
// Released under the MIT License
// https://raw.githubusercontent.com/gkz/prelude-ls/master/LICENSE
"""
